name: Deploy Prod

on:
  push:
    branches:
      - master

env:
  WORKER_ENV: prod
  RUN: ${{github.run_id}}-${{github.run_number}}-${{github.run_attempt}}

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    - run: npm ci
    - run: npm test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{secrets.CLOUDFLARE_API_TOKEN}}
          environment: ${{env.WORKER_ENV}}
          preCommands: echo "*** pre command ***"
        env:
          SOMETHING: ${{env.RUN}}
